#server
server:
  port: 8083
  tomcat:
    max-threads: 1000
#spring datasource
spring:
  datasource:
    url: jdbc:mysql:///enterprisespurchasesellsave?serverTimezone=GMT%2B8&characterEncoding=UTF8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
#Spring mybatis
mybatis:
  type-aliases-package: com.sys.entity
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:/mapper/*.xml
